// app/api/business/idea/interview/route.ts
// POST { ideaId, userMessage: string | null }
//
// Single-turn handler for the adaptive BIZDOC-3/4 interview engine.
//
// BIZDOC-4 additions:
//   - reaction: one honest sentence reacting to the user's answer (from Interviewer)
//   - marketSizing: TAM/SAM/SOM computed in code, generated by cloud on first marketNeed answer
//   - validation tasks: written to Todo table for logged-in users; held in marketSizing JSON for guests
//
// Auth: session-OR-biz-guest ownership guard.

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getTokenFromRequest, verifySessionToken } from "@/lib/session";
import {
  initInterviewState,
  detectSector,
  getProbesForDim,
  CONFIDENCE_THRESHOLD,
  DISAGREEMENT_THRESHOLD,
  MAX_PROBES_PER_DIM,
  type InterviewState,
  type ConversationTurn,
  type DimKey,
  DIMENSIONS,
} from "@/lib/business/interviewConfig";
import { runInterviewer } from "@/lib/business/runInterviewer";
import { runAssessor } from "@/lib/business/runAssessor";
import { runMarketSizing, type MarketSizing } from "@/lib/business/runMarketSizing";

const GUEST_COOKIE = "biz-guest";

// ─── Ownership guard ──────────────────────────────────────────────────────────

async function resolveOwnership(req: NextRequest, ideaId: string) {
  const token = getTokenFromRequest(req);
  const payload = token ? await verifySessionToken(token) : null;
  const sessionUserId = payload?.userId ?? null;
  const guestSessionId = req.cookies.get(GUEST_COOKIE)?.value ?? null;

  const idea = await (db as any).businessIdea.findUnique({
    where: { id: ideaId },
    select: {
      id: true,
      title: true,
      description: true,
      userId: true,
      guestSessionId: true,
      transcript: true,
      interviewState: true,
      dimProvenance: true,
      marketSizing: true,
    },
  });

  if (!idea) return { allowed: false, idea: null, sessionUserId: null };

  const owned = idea.userId
    ? idea.userId === sessionUserId
    : !!guestSessionId && idea.guestSessionId === guestSessionId;

  return { allowed: owned, idea, sessionUserId };
}

// ─── Question bank loader ─────────────────────────────────────────────────────

interface BaseQuestion {
  id: string;
  order: number;
  text: string;
  type: string;
  scoringDim: string;
  options?: { value: string; label: string; score?: number }[];
}

let cachedQuestions: BaseQuestion[] | null = null;

async function loadBaseQuestions(): Promise<BaseQuestion[]> {
  if (cachedQuestions) return cachedQuestions;
  const rows = await (db as any).ideaQuestion.findMany({ orderBy: { order: "asc" } });
  cachedQuestions = rows.map((r: any) => ({
    ...r,
    options: r.options ? (Array.isArray(r.options) ? r.options : JSON.parse(r.options)) : undefined,
  }));
  return cachedQuestions!;
}

// ─── Todo creation for validation tasks ──────────────────────────────────────

async function createValidationTodos(
  userId: string,
  ideaId: string,
  sizing: MarketSizing
): Promise<void> {
  for (const assumption of sizing.assumptions) {
    try {
      await db.todo.create({
        data: {
          userId,
          ideaId,
          title: assumption.validationTask,
          validationLabel: assumption.label,
          successThreshold: assumption.successThreshold,
          // assumptionKey tags this todo so the market-sizing PATCH can reconcile
          // the label when the user adjusts the slider (BIZDOC-5 — replaces freq discriminator)
          assumptionKey: assumption.id,
        },
      });
    } catch (err) {
      // Tolerate duplicate or DB errors — non-blocking
      console.warn("[interview] todo creation failed for assumption", assumption.id, err);
    }
  }
}

// ─── Helper: dim transcript ───────────────────────────────────────────────────

function buildDimTranscript(transcript: ConversationTurn[], dim: DimKey): string {
  return transcript
    .filter((t) => t.role === "user" && t.dim === dim)
    .map((t) => t.content)
    .join("\n");
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { ideaId, userMessage } = body as {
      ideaId: string;
      userMessage: string | null;
    };

    if (!ideaId) {
      return NextResponse.json({ error: "ideaId required" }, { status: 400 });
    }

    const { allowed, idea, sessionUserId } = await resolveOwnership(req, ideaId);
    if (!allowed || !idea) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const baseQuestions = await loadBaseQuestions();

    if (baseQuestions.length === 0) {
      console.error("[Interview] IdeaQuestion table is empty — run `npm run seed:questions`");
      return NextResponse.json(
        { error: "Interview questions not seeded. Run: npm run seed:questions" },
        { status: 500 }
      );
    }

    // ── Init or resume state ────────────────────────────────────────────────

    let state: InterviewState = idea.interviewState
      ? (idea.interviewState as InterviewState)
      : initInterviewState(detectSector(idea.title, idea.description));

    // Backfill: older state objects may not have marketSizingDone
    if (typeof state.marketSizingDone === "undefined") state.marketSizingDone = false;

    let transcript: ConversationTurn[] = (idea.transcript as ConversationTurn[]) ?? [];
    let dimProvenance: Record<string, "local_estimate" | "senior_reviewed"> =
      (idea.dimProvenance as Record<string, "local_estimate" | "senior_reviewed">) ?? {};

    // What was last asked?
    let currentQKey = "";
    let currentQDim: DimKey = "problemClarity";
    let currentQText = "";
    const lastAssistant = [...transcript].reverse().find((t) => t.role === "assistant");
    if (lastAssistant) {
      currentQKey = lastAssistant.questionKey;
      currentQDim = (lastAssistant.dim ?? "problemClarity") as DimKey;
      currentQText = lastAssistant.content;
    }

    let interviewerSource: "local" | "cloud" = "local";
    let reaction: string | null = null;
    let marketSizing: MarketSizing | null =
      (idea.marketSizing as MarketSizing | null) ?? null;
    let marketSizingJustGenerated = false;

    // ── Process user answer ─────────────────────────────────────────────────

    if (userMessage && lastAssistant) {
      // 1. Run local Interviewer (also returns reaction now)
      const iResult = await runInterviewer(
        currentQDim,
        currentQText,
        userMessage,
        state.sector
      );
      interviewerSource = iResult.source;
      reaction = iResult.reaction;
      if (iResult.source === "cloud") state.localUnavailable = true;

      console.log(
        `[Interview] turn dim=${currentQDim} source=${iResult.source}` +
        ` score=${iResult.score} conf=${iResult.confidence.toFixed(2)}` +
        ` followUp=${iResult.followUpNeeded} localUnavailable=${state.localUnavailable}`
      );

      // 2. Update provisional score
      state.provisionalScores[currentQDim] = iResult.score;
      dimProvenance[currentQDim] = "local_estimate";

      // 3. Possibly run cloud Assessor
      const shouldRunAssessor =
        iResult.confidence < CONFIDENCE_THRESHOLD &&
        !state.assessorRun[currentQDim] &&
        !state.localUnavailable;

      if (shouldRunAssessor) {
        const dimTranscript = buildDimTranscript(
          [
            ...transcript,
            { role: "user", content: userMessage, dim: currentQDim, questionKey: currentQKey },
          ],
          currentQDim
        );
        const assessorResult = await runAssessor(
          currentQDim,
          idea.title,
          idea.description,
          state.sector,
          dimTranscript
        );

        if (assessorResult) {
          state.assessorScores[currentQDim] = assessorResult;
          state.assessorRun[currentQDim] = true;
          dimProvenance[currentQDim] = "senior_reviewed";

          const localScore = state.provisionalScores[currentQDim] ?? 0;
          const diff = Math.abs(localScore - assessorResult.score);
          const probeCountHere = state.probeCount[currentQDim] ?? 0;
          if (diff > DISAGREEMENT_THRESHOLD && probeCountHere < MAX_PROBES_PER_DIM) {
            const probes = getProbesForDim(currentQDim, state.sector).filter(
              (p) =>
                !transcript.some((t) => t.questionKey === p.probeId) &&
                !state.probeQueue.some((q) => q.probeId === p.probeId)
            );
            if (probes.length > 0) {
              state.probeQueue.push({
                probeId: probes[0].probeId,
                dim: currentQDim,
                text: probes[0].text,
              });
            }
          }
          state.provisionalScores[currentQDim] = assessorResult.score;
        }
      } else if (
        iResult.followUpNeeded &&
        !state.localUnavailable &&
        !state.assessorRun[currentQDim] &&
        (state.probeCount[currentQDim] ?? 0) < MAX_PROBES_PER_DIM
      ) {
        const usedProbeIds = new Set([
          ...transcript.map((t) => t.questionKey),
          ...state.probeQueue.map((q) => q.probeId),
        ]);
        const probes = getProbesForDim(currentQDim, state.sector).filter(
          (p) => !usedProbeIds.has(p.probeId)
        );
        if (probes.length > 0) {
          state.probeQueue.push({
            probeId: probes[0].probeId,
            dim: currentQDim,
            text: probes[0].text,
          });
        }
      }

      // 4. BIZDOC-4: Market-sizing deepening on first marketNeed answer
      if (
        currentQDim === "marketNeed" &&
        !state.marketSizingDone
      ) {
        state.marketSizingDone = true;
        // Run in background — fire-and-forget so it doesn't block the turn
        runMarketSizing(idea.title, idea.description, state.sector, userMessage)
          .then(async (sizing) => {
            if (!sizing) return;
            await (db as any).businessIdea.update({
              where: { id: ideaId },
              data: { marketSizing: sizing as any },
            });
            // Create validation Todos for logged-in users
            if (sessionUserId) {
              await createValidationTodos(sessionUserId, ideaId, sizing);
            }
            // For guests: sizing already stored on idea JSON — surfaced from idea by the UI
            marketSizing = sizing;
            marketSizingJustGenerated = true;
          })
          .catch((err) => {
            console.warn("[Interview] market sizing background call failed:", err);
          });
      }

      // 5. Append user answer to transcript
      transcript.push({
        role: "user",
        content: userMessage,
        dim: currentQDim,
        questionKey: currentQKey,
      });
    }

    // ── Determine next question ─────────────────────────────────────────────

    let nextQText: string;
    let nextQKey: string;
    let nextQDim: DimKey;
    let done = false;

    const nextProbe = state.probeQueue.shift();
    if (nextProbe) {
      console.log(`[Interview] serving probe id=${nextProbe.probeId} dim=${nextProbe.dim}`);
      nextQText = nextProbe.text;
      nextQKey = nextProbe.probeId;
      nextQDim = nextProbe.dim;
      state.probeCount[nextQDim] = (state.probeCount[nextQDim] ?? 0) + 1;
    } else if (state.currentIndex < baseQuestions.length) {
      console.log(`[Interview] advancing to base Q index=${state.currentIndex} of ${baseQuestions.length} (localUnavailable=${state.localUnavailable})`);
      const baseQ = baseQuestions[state.currentIndex];
      nextQText = baseQ.text;
      nextQKey = baseQ.id;
      nextQDim = baseQ.scoringDim as DimKey;
      state.currentIndex += 1;
    } else {
      console.log(`[Interview] done — all ${baseQuestions.length} base questions answered`);
      done = true;
      nextQText = "";
      nextQKey = "";
      nextQDim = "problemClarity";
    }

    if (!done) {
      transcript.push({
        role: "assistant",
        content: nextQText,
        dim: nextQDim,
        questionKey: nextQKey,
      });
    }

    state.done = done;

    // ── Build provisional output ────────────────────────────────────────────

    const provisional = {
      scores: { ...state.provisionalScores },
      provenance: { ...dimProvenance },
      assessorReasons: Object.fromEntries(
        Object.entries(state.assessorScores).map(([k, v]) => [k, v.reason])
      ),
    };

    const scoreValues = Object.values(provisional.scores);
    const overallScore =
      scoreValues.length > 0
        ? scoreValues.reduce((a, b) => a + b, 0) / scoreValues.length
        : 0;

    // ── Persist ─────────────────────────────────────────────────────────────

    await (db as any).businessIdea.update({
      where: { id: ideaId },
      data: {
        transcript,
        interviewState: state,
        dimProvenance,
      },
    });

    const tier = state.localUnavailable
      ? "cloud-degraded"
      : assessorFiredThisTurn(state, dimProvenance, currentQDim, userMessage)
      ? "senior"
      : "local";

    return NextResponse.json({
      question: nextQText,
      questionKey: nextQKey,
      dim: nextQDim,
      done,
      provisional: { ...provisional, overallScore },
      tier,
      turnNum: transcript.filter((t) => t.role === "user").length,
      reaction,
      // marketSizing is included only when it was just loaded from DB or returned from a previous call
      // The client should poll GET /api/business/idea?id= to get updated marketSizing after turn
      marketSizingPending: currentQDim === "marketNeed" && !idea.marketSizing && userMessage !== null,
    });
  } catch (err) {
    console.error("POST /api/business/idea/interview", err);
    return NextResponse.json({ error: "Interview engine error" }, { status: 500 });
  }
}

function assessorFiredThisTurn(
  state: InterviewState,
  provenance: Record<string, string>,
  lastDim: DimKey,
  userMessage: string | null
): boolean {
  return !!userMessage && provenance[lastDim] === "senior_reviewed";
}
