import React from "react";
import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

// ─── Shared Styles ──────────────────────────────────────────────────────────

const S = StyleSheet.create({
  page: { fontFamily: "Helvetica", fontSize: 9, padding: 40, color: "#111827", backgroundColor: "#fff" },
  heading: { fontSize: 16, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subHeading: { fontSize: 8, color: "#6B7280", marginBottom: 20 },
  label: { fontSize: 7, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 3 },
  divider: { borderBottom: "1pt solid #E5E7EB", marginVertical: 12 },
  footer: {
    position: "absolute", bottom: 30, left: 40, right: 40,
    borderTopWidth: 1, borderTopColor: "#E5E7EB", borderTopStyle: "solid",
    paddingTop: 6, flexDirection: "row", justifyContent: "space-between",
  },
  footerText: { fontSize: 7, color: "#9CA3AF" },
  badge: { backgroundColor: "#F3F4F6", padding: "3 8", borderRadius: 4, fontSize: 8, color: "#374151", alignSelf: "flex-start", marginBottom: 12 },
  // SWOT
  swotGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  swotCell: { width: "48%", minHeight: 120, padding: 10, borderRadius: 4, marginBottom: 8, borderWidth: 1, borderStyle: "solid" },
  swotTitle: { fontSize: 8, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  swotText: { fontSize: 8, color: "#374151", lineHeight: 1.5 },
  // BMC
  bmcRow: { flexDirection: "row", marginBottom: 4 },
  bmcCell: { flex: 1, padding: 8, borderRadius: 3, marginRight: 4, minHeight: 60, borderWidth: 1, borderStyle: "solid" },
  bmcTitle: { fontSize: 7, fontFamily: "Helvetica-Bold", color: "#6B7280", marginBottom: 4, textTransform: "uppercase" },
  bmcText: { fontSize: 8, color: "#374151", lineHeight: 1.4 },
  // Financials
  tableHeader: { flexDirection: "row", backgroundColor: "#F9FAFB", padding: "6 4", borderBottom: "1pt solid #E5E7EB" },
  tableRow: { flexDirection: "row", padding: "5 4", borderBottom: "1pt solid #F3F4F6" },
  tableRowAlt: { flexDirection: "row", padding: "5 4", borderBottom: "1pt solid #F3F4F6", backgroundColor: "#FAFAFA" },
  tableRowBold: { flexDirection: "row", padding: "5 4", borderTop: "1pt solid #E5E7EB", backgroundColor: "#F9FAFB" },
  cellLabel: { flex: 3, fontSize: 9 },
  cellNum: { flex: 2, textAlign: "right", fontSize: 9 },
  cellHead: { fontFamily: "Helvetica-Bold", fontSize: 8, color: "#6B7280" },
  cellBold: { fontFamily: "Helvetica-Bold" },
  profitPos: { color: "#16A34A" },
  profitNeg: { color: "#DC2626" },
});

const genDate = () =>
  new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

// ─── SWOT PDF ───────────────────────────────────────────────────────────────

export type SWOTContent = { strengths: string; weaknesses: string; opportunities: string; threats: string };

export function SWOTPdf({ title, content }: { title: string; content: SWOTContent }) {
  const date = genDate();
  const quadrants = [
    { key: "strengths" as const, label: "Strengths (Internal)", bg: "#F0FDF4", border: "#86EFAC" },
    { key: "weaknesses" as const, label: "Weaknesses (Internal)", bg: "#FEF2F2", border: "#FCA5A5" },
    { key: "opportunities" as const, label: "Opportunities (External)", bg: "#EFF6FF", border: "#93C5FD" },
    { key: "threats" as const, label: "Threats (External)", bg: "#FFFBEB", border: "#FCD34D" },
  ];

  return (
    <Document>
      <Page size="A4" style={S.page}>
        <Text style={S.badge}>SWOT ANALYSIS</Text>
        <Text style={S.heading}>{title}</Text>
        <Text style={S.subHeading}>Generated by Charaivati · {date}</Text>
        <View style={S.divider} />
        <View style={S.swotGrid}>
          {quadrants.map((q) => (
            <View key={q.key} style={{ ...S.swotCell, backgroundColor: q.bg, borderColor: q.border }}>
              <Text style={S.swotTitle}>{q.label}</Text>
              <Text style={S.swotText}>{content[q.key] || "—"}</Text>
            </View>
          ))}
        </View>
        <View style={S.footer} fixed>
          <Text style={S.footerText}>Charaivati Business Plan · charaivati.com</Text>
          <Text style={S.footerText}>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}

// ─── BMC PDF ────────────────────────────────────────────────────────────────

export type BMCContent = {
  keyPartners: string; keyActivities: string; keyResources: string;
  valuePropositions: string; customerRelationships: string; channels: string;
  customerSegments: string; costStructure: string; revenueStreams: string;
};

export function BMCPdf({ title, content }: { title: string; content: BMCContent }) {
  const date = genDate();
  const defCell = { ...S.bmcCell, backgroundColor: "#F9FAFB", borderColor: "#E5E7EB" };
  const transparent = { ...S.bmcCell, backgroundColor: "transparent", borderWidth: 0 };

  return (
    <Document>
      <Page size="A4" style={S.page} orientation="landscape">
        <Text style={S.badge}>BUSINESS MODEL CANVAS</Text>
        <Text style={S.heading}>{title}</Text>
        <Text style={S.subHeading}>Generated by Charaivati · {date}</Text>
        <View style={S.divider} />

        {/* Row 1 */}
        <View style={S.bmcRow}>
          <View style={defCell}>
            <Text style={S.bmcTitle}>Key Partners</Text>
            <Text style={S.bmcText}>{content.keyPartners || "—"}</Text>
          </View>
          <View style={defCell}>
            <Text style={S.bmcTitle}>Key Activities</Text>
            <Text style={S.bmcText}>{content.keyActivities || "—"}</Text>
          </View>
          <View style={{ ...S.bmcCell, backgroundColor: "#F5F3FF", borderColor: "#C4B5FD" }}>
            <Text style={S.bmcTitle}>Value Propositions</Text>
            <Text style={S.bmcText}>{content.valuePropositions || "—"}</Text>
          </View>
          <View style={defCell}>
            <Text style={S.bmcTitle}>Customer Relationships</Text>
            <Text style={S.bmcText}>{content.customerRelationships || "—"}</Text>
          </View>
          <View style={{ ...S.bmcCell, marginRight: 0, backgroundColor: "#EFF6FF", borderColor: "#93C5FD" }}>
            <Text style={S.bmcTitle}>Customer Segments</Text>
            <Text style={S.bmcText}>{content.customerSegments || "—"}</Text>
          </View>
        </View>

        {/* Row 2 */}
        <View style={S.bmcRow}>
          <View style={transparent} />
          <View style={defCell}>
            <Text style={S.bmcTitle}>Key Resources</Text>
            <Text style={S.bmcText}>{content.keyResources || "—"}</Text>
          </View>
          <View style={transparent} />
          <View style={defCell}>
            <Text style={S.bmcTitle}>Channels</Text>
            <Text style={S.bmcText}>{content.channels || "—"}</Text>
          </View>
          <View style={{ ...transparent, marginRight: 0 }} />
        </View>

        {/* Row 3 */}
        <View style={S.bmcRow}>
          <View style={{ ...S.bmcCell, flex: 2.5, backgroundColor: "#FEF2F2", borderColor: "#FECACA" }}>
            <Text style={S.bmcTitle}>Cost Structure</Text>
            <Text style={S.bmcText}>{content.costStructure || "—"}</Text>
          </View>
          <View style={{ ...S.bmcCell, flex: 2.5, marginRight: 0, backgroundColor: "#F0FDF4", borderColor: "#86EFAC" }}>
            <Text style={S.bmcTitle}>Revenue Streams</Text>
            <Text style={S.bmcText}>{content.revenueStreams || "—"}</Text>
          </View>
        </View>

        <View style={S.footer} fixed>
          <Text style={S.footerText}>Charaivati Business Plan · charaivati.com</Text>
          <Text style={S.footerText}>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}

// ─── Financials PDF ─────────────────────────────────────────────────────────

export type YearFinancials = { revenue: string; cogs: string; operatingCosts: string; marketingCosts: string; otherCosts: string };
export type FinancialsContent = { year1: YearFinancials; year2: YearFinancials; year3: YearFinancials };

function fmtINR(s: string): string {
  const n = parseFloat(s);
  if (!s || isNaN(n)) return "—";
  return `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

function totalCosts(y: YearFinancials): number {
  return (parseFloat(y.cogs) || 0) + (parseFloat(y.operatingCosts) || 0) + (parseFloat(y.marketingCosts) || 0) + (parseFloat(y.otherCosts) || 0);
}

function netProfit(y: YearFinancials): number {
  return (parseFloat(y.revenue) || 0) - totalCosts(y);
}

export function FinancialsPdf({ title, content }: { title: string; content: FinancialsContent }) {
  const date = genDate();
  const years = [
    { key: "year1" as const, label: "Year 1" },
    { key: "year2" as const, label: "Year 2" },
    { key: "year3" as const, label: "Year 3" },
  ];

  const rows: { label: string; getValue: (y: YearFinancials) => string; bold?: boolean; isProfit?: boolean }[] = [
    { label: "Total Revenue", getValue: (y) => fmtINR(y.revenue) },
    { label: "Cost of Goods Sold", getValue: (y) => fmtINR(y.cogs) },
    { label: "Operating Costs", getValue: (y) => fmtINR(y.operatingCosts) },
    { label: "Marketing Costs", getValue: (y) => fmtINR(y.marketingCosts) },
    { label: "Other Costs", getValue: (y) => fmtINR(y.otherCosts) },
    { label: "Total Costs", getValue: (y) => fmtINR(String(totalCosts(y))), bold: true },
    { label: "Net Profit / Loss", getValue: (y) => fmtINR(String(netProfit(y))), bold: true, isProfit: true },
  ];

  return (
    <Document>
      <Page size="A4" style={S.page}>
        <Text style={S.badge}>3-YEAR FINANCIAL PLAN</Text>
        <Text style={S.heading}>{title}</Text>
        <Text style={S.subHeading}>
          All amounts in ₹ (INR). Estimates for planning purposes only. Generated by Charaivati · {date}
        </Text>
        <View style={S.divider} />

        <View style={S.tableHeader}>
          <Text style={{ ...S.cellLabel, ...S.cellHead }}>Metric</Text>
          {years.map((yr) => (
            <Text key={yr.key} style={{ ...S.cellNum, ...S.cellHead }}>{yr.label}</Text>
          ))}
        </View>

        {rows.map((row, i) => {
          const rowStyle = row.bold ? S.tableRowBold : i % 2 === 0 ? S.tableRow : S.tableRowAlt;
          const labelStyle = row.bold ? { ...S.cellLabel, ...S.cellBold } : S.cellLabel;
          return (
            <View key={row.label} style={rowStyle}>
              <Text style={labelStyle}>{row.label}</Text>
              {years.map((yr) => {
                const val = row.getValue(content[yr.key]);
                const profit = row.isProfit ? netProfit(content[yr.key]) : null;
                const colorStyle =
                  profit !== null
                    ? profit > 0 ? S.profitPos : profit < 0 ? S.profitNeg : {}
                    : {};
                const numStyle = row.bold
                  ? { ...S.cellNum, ...S.cellBold, ...colorStyle }
                  : { ...S.cellNum, ...colorStyle };
                return (
                  <Text key={yr.key} style={numStyle}>{val}</Text>
                );
              })}
            </View>
          );
        })}

        <View style={S.footer} fixed>
          <Text style={S.footerText}>Charaivati Business Plan · charaivati.com</Text>
          <Text style={S.footerText}>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}
